added hook

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,4 +1,12 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
-npx lint-staged
+npm run check-lint ||(
+  echo 'Failed in syntax please correct indextation errors and some of mentioned above' false;
+)
+echo 'Alright code is fine  trying to build'
+
+npm run build ||(
+  echo 'there sre some error please resolve those errors and commit after'
+  false;
+)
