some changes

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,8 +1,6 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
-npm run lint-fix ||(
-  echo 'Fixed all syntactical errors Please commit again and push it to git'
-  false;
+npm run check-lint ||(
+  echo 'Failed to commit there are syntactical error please resolve it and commit again or try fixing by `npm run lint-fix`'
 )
-npm run lint-fix || false;
